# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: raghugv7/hello-docker

steps:
- task: Docker@2
  displayName: Build Image
  inputs:
   repository: $(imageName)
   command: build
   Dockerfile: Dockerfile

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(DockerHub)
    repository: $(imageName)
    command: push
    tags: |
      $(Build.BuildNumber)
      latest